version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"     # REST
      - "6334:6334"     # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - "1865:80"
      - "8080:8080"
    restart: unless-stopped
    environment:
      CAT_LLM_PROVIDER: "ollama"
      CAT_LLM_BASE_URL: "http://ollama:11434"
      CAT_LLM_MODEL: "llama3.2:3b"
    volumes:
      - "C:/Users/Ale/Desktop/cheshire_cat/static:/app/cat/static"
      - "C:/Users/Ale/Desktop/cheshire_cat/plugins:/app/cat/plugins"
      - "C:/Users/Ale/Desktop/cheshire_cat/data:/app/cat/data"

volumes:
  ollama_models:
