version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"     # REST
      - "6334:6334"     # gRPC
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__STORAGE__WAL__F_SYNC=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - qdrant_data:/qdrant/storage    # <-- named volume, evita corruzioni su FS host

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    restart: unless-stopped
    ports:
      - "1865:80"        # Admin UI
      - "8080:8080"      # Chat API (se esposta)
    environment:
      CAT_LLM_PROVIDER: "ollama"
      CAT_LLM_BASE_URL: "http://ollama:11434"
      CAT_LLM_MODEL: "llama3.1:8b"
      CCAT_LOG_LEVEL: "DEBUG"
    depends_on:
      - qdrant
      - ollama
    volumes:
      - "C:/Users/Ale/Desktop/cheshire_cat/static:/app/cat/static"
      - "C:/Users/Ale/Desktop/cheshire_cat/plugins:/app/cat/plugins"
      - "C:/Users/Ale/Desktop/cheshire_cat/data:/app/cat/data"

volumes:
  qdrant_data:
  ollama_models:
